version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    steps:
      - run:
          name: Install Wine
          command: |
            sudo dpkg --add-architecture i386 && sudo apt-get update
            sudo apt-get install wine32 -y
            sudo ln -s /usr/bin/wine32 /usr/bin/wine

      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run lint

      - run:
          name: Build app for Linux
          command: |
            npm run pack -- --targets linux
            cd dist && tar czf ./RemoteStack-Player-linux-b$(echo $CIRCLE_BUILD_NUM).tar.gz ./RemoteStack-Player-linux
            rm -r ./dist/RemoteStack-Player-linux

      - run:
          name: Build app for Mac
          command: |
            npm run pack -- --targets mac
            cd dist && tar czf ./RemoteStack-Player-mac-b$(echo $CIRCLE_BUILD_NUM).tar.gz ./RemoteStack-Player-mac
            rm -r ./dist/RemoteStack-Player-mac

      - run:
          name: Build app for Windows
          command: |
            npm run pack -- --targets win
            cd dist && tar czf ./RemoteStack-Player-win-b$(echo $CIRCLE_BUILD_NUM).tar.gz ./RemoteStack-Player-win
            rm -r ./dist/RemoteStack-Player-win


      # - run: npm run pack -- --targets linux,mac,win
      #
      # - run: cd dist && tar czf ./RemoteStack-Player-linux-b$(echo $CIRCLE_BUILD_NUM).tar.gz ./RemoteStack-Player-linux
      # - run: cd dist && tar czf ./RemoteStack-Player-mac-b$(echo $CIRCLE_BUILD_NUM).tar.gz ./RemoteStack-Player-mac
      # - run: cd dist && tar czf ./RemoteStack-Player-win-b$(echo $CIRCLE_BUILD_NUM).tar.gz ./RemoteStack-Player-win
      #
      # - run: rm -r ./dist/RemoteStack-Player-linux
      # - run: rm -r ./dist/RemoteStack-Player-mac
      # - run: rm -r ./dist/RemoteStack-Player-win

      - store_artifacts:
          path: ./dist
